version: "2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_DATABASE=gambioDb
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=654321
      - MYSQL_HOST=db
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - "6603:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=654321
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=654321
      - MYSQL_DATABASE=gambioDb
    volumes:
      - "mysql_data:/var/lib/mysql"
      - ./data/schema.sql:/docker-entrypoint-initdb.d/schema.sql
volumes:
  mysql_data: { driver: local }
